### ISSUE TITLE
General Debt Dispute tool debt type field can be left empty

### ISSUE THREAD

**Issue by orlando** [debtcollective/dispute-tools#169]
Validation is not working correctly when you have many debt types. We are storing in this case debts as a JSON array with the following structure

```ts
{ debts: [{ type: string, amount: number}] }
```

## Acceptance Criteria

- App should validate the presence of both type and amount for each debt the users adds in the General Debt Dispute tool

**Comment by duranmla** [comment]
As an update: Currently, while I have added the custom validation to check for object shapes, there still the issue that the data to be checked is actually no the same that we send out to the server.

![image](https://user-images.githubusercontent.com/1425162/56382105-de4e8080-6216-11e9-8ee6-08ab1d9c4e07.png)

As the picture illustrate the `debts` key only has a string instead of an object `{ type, amount }` so in order to make everything work as expected we need that shape to be present in the validation time.

I need to solve that part to make the PR

**Comment by duranmla** [comment]
After the brainstorming to the approach to solving this I am going to aim to:

- [ ]  Find how to get the values in a Vue component from its template inputs
- [ ]  Add a method that returns the value as an object `{ type: string, amount: number }`
- [ ]  Inject over `getFieldValues` the code to handle special `debts` key type

**Comment by duranmla** [comment]
I have added the code necessary after the comment above, we are missing now the display of the error before making the PR and minor updates to the validation function.

**Comment by duranmla** [comment]
Ultimately, the last issue now is that after everything seems to pass the submit fails like so: http://recordit.co/j3kqH1xBz9.gif

**Comment by duranmla** [comment]
The problem is that the backend makes a validation with a different input than the frontend, with that being said I'm going to fix it and it should be all for this PR.
